#!/bin/bash
set -euo pipefail

DOC="Connected Sets"
DIR="/www/complex-analysis"
HOST=www.eul.ink
LOGIN=boisgera

# Helpers
# ------------------------------------------------------------------------------
escape () {
  echo $(printf %q "$1")
}

me="$LOGIN@$HOST"
target="$DIR"/$(escape "$DOC")

# Main
# ------------------------------------------------------------------------------
ssh "$me" mkdir -p "$target"

# Documents and Archive
exts=(txt json html pdf zip)
files=()
for ext in "${exts[@]}"
do
  files+=("$DOC.$ext")
done

# Images
if [ -e images ]; then
  files+=("images")
fi

# Bibliography
files+=($(ls -d *.bib 2>/dev/null || true))

# Ship
rsync -av "${files[@]}" "$me:$target"

